default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  port: 5434
  username: postgres
  password: password
  host: 127.0.0.1
  database: bet_conductor_development

test:
  <<: *default
  database: bet_conductor_test

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') %>